name: Run Diagnostics

on:
  push: 
    branches: ["main"]

jobs:
  run-diagnostics:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install -e.

      - name: Process test data
        run: |
          source .venv/bin/activate
          python freemocap/diagnostics/run_test_data.py

      - name: Calculate diagnostics
        run: |
          source .venv/bin/activate
          python freemocap/diagnostics/calculate_diagnostics.py

      - name: Generate diagnostic report
        run: |
          uv pip install jinja2
          source .venv/bin/activate
          python freemocap/diagnostics/generate_diagnostic_report.
          
      - name: Upload diagnostic report
        uses: actions/upload-artifact@v4
        with:
          name: diagnostic_report
          path: freemocap/diagnostics/version_diagnostics/diagnostic_report.html





