name: Run Diagnostics

on:
  push: 
    branches: ["main"]

jobs:
  run-diagnostics:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
      fail-fast: false

    runs-on: ${{ matrix.os }}
    
    env:
      # Windows-specific environment variables (will be ignored on other platforms)
      PYTHONIOENCODING: utf-8
      PYTHONLEGACYWINDOWSSTDIO: ${{ runner.os == 'Windows' && '1' || '' }}
      PYTHONUTF8: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install uv
          uv venv
          uv pip install -e .

      - name: Process test data (Windows)
        if: runner.os == 'Windows'
        run: |
          .\.venv\Scripts\python freemocap/diagnostics/run_test_data.py

      - name: Process test data (Unix)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          python freemocap/diagnostics/run_test_data.py

      - name: Calculate diagnostics (Windows)
        if: runner.os == 'Windows'
        run: |
          .\.venv\Scripts\python freemocap/diagnostics/calculate_diagnostics.py

      - name: Calculate diagnostics (Unix)
        if: runner.os != 'Windows'
        run: |
          source .venv/bin/activate
          python freemocap/diagnostics/calculate_diagnostics.py

      - name: Generate diagnostic report (Windows)
        if: runner.os == 'Windows'
        run: |
          uv pip install jinja2
          .\.venv\Scripts\python freemocap/diagnostics/generate_diagnostic_report.py
          
      - name: Generate diagnostic report (Unix)
        if: runner.os != 'Windows'
        run: |
          uv pip install jinja2
          source .venv/bin/activate
          python freemocap/diagnostics/generate_diagnostic_report.py
          
      - name: Upload diagnostic report
        uses: actions/upload-artifact@v4
        with:
          name: diagnostic_report-${{ matrix.os }}
          path: freemocap/diagnostics/version_diagnostics/diagnostic_report.html